package com.lcc_megapremium.megapremium_lcc.Model.ENUM;

public enum EnumRegrasEstatisticas {

    ESTATISTICA_NUM_MAIS_CAEM,
    ESTATISTICA_PARES_IMPARES,
    ESTATISTICA_PRIMOS,
    ESTATISTICA_FIBONACCI,
    ESTATISTICA_SORTEIOS_LINHAS,
    ESTATISTICA_SORTEIOS_COLUNAS,
    ESTATISTICA_CONSECUTIVOS,
    ESTATISTICA_QUADRANTES_MAIS_SAEM,
    ESTATISTICA_ANALIZA_HISTORICO_SEQUENCIA,
    ESTATISTICA_ESTRUTURA_SEQUENCIA_PADRAO,
    ESTATISTICA_DIFERENCA_PADRAO_ELEMENTOS,
    ESTATISTICA_ANALIZA_ELEMENTOS_GEMEOS;
}
